DROP TABLE IF EXISTS wcf1_navigation;
CREATE TABLE wcf1_navigation (
	navigationID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	packageID INT(10) NOT NULL DEFAULT 0,
	title VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_navigation_item;
CREATE TABLE wcf1_navigation_item (
	navigationItemID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	navigationID INT(10) NOT NULL DEFAULT 0,
	navigationItem VARCHAR(255) NOT NULL DEFAULT '',
	url VARCHAR(255) NOT NULL DEFAULT '',
	icon VARCHAR(255) NOT NULL DEFAULT '',
	showOrder INT(10) NOT NULL DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8;